[package]
name = "localtunnel"
version = "0.0.8"
edition = "2021"
description = "A client to connect with localtunnel server."
license = "Apache-2.0"
repository = "https://github.com/kaichaosun/rlt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
anyhow = { version = "1.0.56", features = ["backtrace"] }
log = "0.4"
