[package]
name = "rlt-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
futures-util = "0.3"
tokio-util = "0.7.3"
anyhow = { version = "1.0.56", features = ["backtrace"] }