[package]
name = "localtunnel-cli"
version = "0.0.3"
edition = "2021"
description = "A CLI to proxy with localtunnel server."
license = "Apache-2.0"
repository = "https://github.com/kaichaosun/rlt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
localtunnel = { path = "../client", version = "0.0.9" }
tokio = { version = "1.19.2", features = ["full"] }
log = "0.4"
env_logger = "0.9"
