[package]
name = "localtunnel-cli"
version = "0.0.1"
edition = "2021"
description = "A CLI to proxy with localtunnel server."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
localtunnel = { path = "../client", version = "0.0.7" }
tokio = { version = "1.19.2", features = ["full"] }
