[package]
name = "localtunnel-cli"
version = "0.0.2"
edition = "2021"
description = "A CLI to proxy with localtunnel server."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
localtunnel = { path = "../client" }
tokio = { version = "1.19.2", features = ["full"] }
