[package]
name = "rlt-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlt-client = { path = "../client" }
tokio = { version = "1", features = ["full"] }
