[package]
name = "localtunnel-server"
version = "0.0.1"
edition = "2021"
description = "Server implementation of localtunnel."
license = "Apache-2.0"
repository = "https://github.com/kaichaosun/rlt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
anyhow = { version = "1.0.56", features = ["backtrace"] }
log = "0.4"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
tldextract = "0.6.0"
sni_rs = "1.0.0"
pin-project = "1"
byteorder = "1"